# Generated by Django 2.2.9 on 2020-08-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='model',
            field=models.CharField(max_length=201, verbose_name='关联模型'),
        ),
    ]
