# Generated by Django 2.2.9 on 2020-09-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='combinator',
            field=models.CharField(choices=[('&', '与'), ('|', '或')], default='&', max_length=1, verbose_name='组合方式'),
        ),
    ]
