# Generated by Django 2.1.2 on 2018-10-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20181012_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Ship', verbose_name='船'),
        ),
    ]
