# Generated by Django 2.1.3 on 2019-05-09 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('icon', models.CharField(blank=True, help_text='请使用AntDesign的图标名', max_length=100, null=True, verbose_name='图标名')),
                ('path', models.CharField(help_text='前端功能页面的路径', max_length=200, verbose_name='路径')),
                ('permission', models.CharField(help_text='格式有<app_label>.<codename>', max_length=200, verbose_name='关联权限')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType', verbose_name='关联模型')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bsm_config.Menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '导航菜单',
                'verbose_name_plural': '导航菜单',
            },
        ),
    ]
