# Generated by Django 2.1.3 on 2019-05-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='content_type',
        ),
        migrations.AddField(
            model_name='menu',
            name='model',
            field=models.CharField(blank=True, help_text='格式为：<app_label>__<model>', max_length=200, null=True, verbose_name='关联模型'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, help_text='请使用AntDesign的图标:https://ant.design/components/icon-cn/', max_length=100, null=True, verbose_name='图标名'),
        ),
    ]
