# Generated by Django 2.1.3 on 2019-05-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0002_auto_20190509_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='path',
        ),
        migrations.AddField(
            model_name='menu',
            name='page',
            field=models.CharField(default='list', help_text='前端功能页面的标识', max_length=200, verbose_name='页面'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='permission',
            field=models.CharField(blank=True, help_text='格式有<app_label>.<codename>', max_length=200, null=True, verbose_name='关联权限'),
        ),
    ]
