# Generated by Django 2.1.3 on 2019-05-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0003_auto_20190509_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='数值越小，排列越前', verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.CharField(blank=True, default='list', help_text='前端功能页面的标识', max_length=200, null=True, verbose_name='页面'),
        ),
    ]
