# Generated by Django 2.1.3 on 2019-07-09 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0004_auto_20190510_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='bsm_config.Menu', verbose_name='上级菜单'),
        ),
    ]
