# Generated by Django 2.1.3 on 2019-07-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0005_auto_20190709_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sequence',
            field=models.PositiveIntegerField(default=1000, help_text='数值越小，排列越前', verbose_name='排序'),
        ),
    ]
