# Generated by Django 2.2 on 2020-01-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0007_auto_20200102_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sequence',
            field=models.IntegerField(default=1000, help_text='数值越小，排列越前', verbose_name='排序'),
        ),
    ]
