# Generated by Django 2.2.9 on 2020-02-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0008_auto_20200120_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True, verbose_name='配置键')),
                ('value', models.CharField(max_length=255, verbose_name='配置值')),
                ('type', models.CharField(choices=[('string', '字符串'), ('text', '文本'), ('integer', '整型'), ('float', '浮点数'), ('decimal', '小数'), ('bool', 'Boolean值'), ('time', '时间'), ('date', '日期'), ('datetime', '日期时间'), ('image', '图片'), ('file', '文件')], default='string', max_length=30, verbose_name='键类型')),
                ('display_name', models.CharField(max_length=30, verbose_name='中文名')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义路径'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.CharField(blank=True, choices=[['list', '列表页'], ['detail', '详情页'], ['adminConfig', '页面配置面板'], ['auto', '自定义页面']], default='list', help_text='前端功能页面的标识', max_length=200, null=True, verbose_name='页面'),
        ),
    ]
