# Generated by Django 2.2.9 on 2020-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0009_auto_20200226_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='配置值'),
        ),
    ]
