# Generated by Django 2.2.9 on 2020-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0010_auto_20200226_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='名称'),
        ),
    ]
