# Generated by Django 2.2 on 2020-04-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0011_auto_20200410_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='model',
            field=models.CharField(max_length=100, verbose_name='模型名称'),
        ),
    ]
