# Generated by Django 2.2.9 on 2020-04-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0012_auto_20200417_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(max_length=255, null=True, verbose_name='配置值'),
        ),
    ]
