# Generated by Django 2.2.9 on 2020-05-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('bsm_config', '0017_auto_20200511_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='设置可查看此菜单的角色', related_name='groups', to='auth.Group', verbose_name='关联角色'),
        ),
    ]
