# Generated by Django 2.2.9 on 2020-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0018_menu_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='仅管理员可看'),
        ),
    ]
