# Generated by Django 2.2.9 on 2020-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0020_auto_20200530_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.TextField(null=True, verbose_name='配置值'),
        ),
    ]
