# Generated by Django 2.2.9 on 2020-06-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0021_auto_20200531_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='设置可查看此菜单的角色', related_name='menus', to='auth.Group', verbose_name='关联角色'),
        ),
    ]
