# Generated by Django 2.2.9 on 2020-06-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0022_auto_20200602_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='help_text',
            field=models.CharField(blank=True, max_length=225, null=True, verbose_name='提示信息'),
        ),
    ]
