# Generated by Django 2.2.9 on 2020-08-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0026_auto_20200722_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='model',
            field=models.CharField(max_length=100, unique=True, verbose_name='模型名称'),
        ),
    ]
