# Generated by Django 2.2.9 on 2020-11-26 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_auto_20201125_0722'),
        ('bsm_config', '0030_fieldadmin_fieldpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='puzzle.Page', verbose_name='指向页面'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='page',
            field=models.CharField(choices=[['list', '列表页'], ['detail', '详情页'], ['adminConfig', '页面配置面板'], ['auto', '自定义页面'], ['chart', '自定义图表'], ['iframe', 'Iframe页面']], default='', help_text='前端功能页面的标识', max_length=200, null=True, verbose_name='页面类型'),
        ),
    ]
