# Generated by Django 2.2.9 on 2020-12-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0031_auto_20201203_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='限制可查看此菜单的角色，留空则不限制', related_name='menus', to='auth.Group', verbose_name='可见角色'),
        ),
    ]
