# Generated by Django 2.2.9 on 2020-12-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0032_auto_20201126_1802'),
        ('bsm_config', '0033_auto_20201203_1558'),
    ]

    operations = [
    ]
