# Generated by Django 2.2.17 on 2021-03-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0034_merge_20201205_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='view',
            field=models.CharField(help_text='自定义视图名，非模型的默认列表', max_length=200, null=True, verbose_name='视图'),
        ),
    ]
