# Generated by Django 2.2.17 on 2021-03-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsm_config', '0035_menu_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='view',
            field=models.CharField(blank=True, help_text='自定义视图名，非模型的默认列表', max_length=200, null=True, verbose_name='视图'),
        ),
    ]
