"""api相关常量"""

OPERATION_LIST = 'list'
OPERATION_RETRIEVE = 'retrieve'
OPERATION_CREATE = 'create'
OPERATION_UPDATE = 'update'
OPERATION_REPLACE = 'replace'
OPERATION_DELETE = 'delete'
OPERATION_UPDATE_BY_CONDITION = 'update_by_condition'
OPERATION_DELETE_BY_CONDITION = 'delete_by_condition'
OPERATION_FUNC = 'func'

OPERATIONS_CHOICES = (
    (OPERATION_LIST, '查看'),
    (OPERATION_RETRIEVE, '详情'),
    (OPERATION_CREATE, '新建'),
    (OPERATION_UPDATE, '全部更新'),
    (OPERATION_REPLACE, '部分更新'),
    (OPERATION_DELETE, '删除'),
    (OPERATION_UPDATE_BY_CONDITION, '批量更新'),
    (OPERATION_DELETE_BY_CONDITION, '批量删除'),
    (OPERATION_FUNC, '云函数'),
)

OPERATIONS = set([t[0] for t in OPERATIONS_CHOICES])

MATHOD_GET = 'get'
MATHOD_POST = 'post'
MATHOD_PUT = 'put'
MATHOD_DELETE = 'delete'
MATHOD_PATCH = 'patch'

METHOD_MAP = {
    OPERATION_LIST: (MATHOD_GET,),
    OPERATION_RETRIEVE: (MATHOD_GET,),
    OPERATION_CREATE: (MATHOD_POST,),
    OPERATION_UPDATE: (MATHOD_PUT,),
    OPERATION_REPLACE: (MATHOD_PATCH, MATHOD_PUT),
    OPERATION_DELETE: (MATHOD_DELETE,),
    OPERATION_UPDATE_BY_CONDITION: (MATHOD_PATCH, MATHOD_PUT),
    OPERATION_DELETE_BY_CONDITION: (MATHOD_DELETE,),
    OPERATION_FUNC: (MATHOD_POST,),
}

TYPE_STRING = 'string'
TYPE_INT = 'int'
TYPE_DECIMAL = 'decimal'
TYPE_BOOLEAN = 'boolean'
TYPE_JSON = 'json'
TYPE_OBJECT = 'object'
TYPE_PAGE_SIZE = 'PAGE_SIZE'
TYPE_PAGE_IDX = 'PAGE_IDX'
TYPE_PK = 'pk'
TYPES_CHOICES = (
    (TYPE_STRING, '字符串'),
    (TYPE_INT, '整数'),
    (TYPE_DECIMAL, '浮点数'),
    (TYPE_BOOLEAN, '布尔值'),
    (TYPE_JSON, 'json格式'),
    (TYPE_OBJECT, '复杂类型'),
    (TYPE_PAGE_SIZE, '页长'),
    (TYPE_PAGE_IDX, '页码'),
    (TYPE_PK, '主键'),
)
TYPES = set([t[0] for t in TYPES_CHOICES])

SPECIAL_TYPES = (TYPE_PAGE_SIZE, TYPE_PAGE_IDX, TYPE_PK)

FILTER_TYPE_CONTAINER = 0  # 容器
FILTER_TYPE_CHILD = 1  # 单一条件

DRIVER_DB = 'db'
DRIVER_JS = 'js'
