# Generated by Django 2.2.17 on 2021-05-24 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightning_code', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functions', to='lightning_code.Category', verbose_name='目录'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='function',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lightning_code.Function', verbose_name='函数'),
        ),
    ]
