# Generated by Django 2.2.17 on 2021-05-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightning_code', '0002_auto_20210524_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lightning_code.Category', verbose_name='上级目录'),
        ),
    ]
