# Generated by Django 2.2.17 on 2021-05-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightning_code', '0003_auto_20210524_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lightning_code.Tag', verbose_name='标签'),
        ),
    ]
