# Generated by Django 2.2.9 on 2020-11-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='id',
        ),
        migrations.RemoveField(
            model_name='page',
            name='root',
        ),
        migrations.AddField(
            model_name='page',
            name='block_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.Block'),
            preserve_default=False,
        ),
    ]
