# Generated by Django 2.2.9 on 2020-11-26 18:02

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_auto_20201125_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='puzzle.Block', verbose_name='父结点'),
        ),
    ]
