# Generated by Django 2.2.17 on 2021-04-23 10:10

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_auto_20201126_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='模型')),
                ('display', jsonfield.fields.JSONField(default=[], verbose_name='列表字段')),
                ('filter', jsonfield.fields.JSONField(default=[], verbose_name='过滤字段')),
                ('inlineActions', jsonfield.fields.JSONField(default=[], verbose_name='操作项')),
                ('actions', jsonfield.fields.JSONField(default=[], verbose_name='批量操作')),
                ('tableActions', jsonfield.fields.JSONField(default=[], verbose_name='全局操作')),
                ('sortable', jsonfield.fields.JSONField(default=[], verbose_name='排序字段')),
                ('filterLayout', jsonfield.fields.JSONField(default='default', verbose_name='过滤布局')),
                ('block', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Block', verbose_name='渲染结点')),
            ],
        ),
    ]
