# Generated by Django 2.2.17 on 2021-04-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='table',
            name='filterLayout',
            field=models.CharField(default='default', max_length=255, verbose_name='滤布局'),
        ),
    ]
