# Generated by Django 2.2.17 on 2021-05-24 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0005_auto_20210426_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': '表格', 'verbose_name_plural': '表格'},
        ),
    ]
