# Generated by Django 2.1.3 on 2019-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0003_api_field_filter_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(choices=[('CONTAINER', '容器'), ('CHILD', '单一条件')], max_length=50, verbose_name='条件类型'),
        ),
    ]
