# Generated by Django 2.1.3 on 2019-09-10 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0005_auto_20190910_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='parenet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_basebone.Filter', verbose_name='parenet'),
        ),
    ]
