# Generated by Django 2.1.3 on 2019-09-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0007_auto_20190910_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filter',
            old_name='name',
            new_name='field',
        ),
    ]
