# Generated by Django 2.1.3 on 2019-09-11 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0008_auto_20190910_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['name'], 'verbose_name': 'API的字段', 'verbose_name_plural': 'API的字段'},
        ),
        migrations.RemoveField(
            model_name='filter',
            name='parenet',
        ),
        migrations.AddField(
            model_name='filter',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_basebone.Filter', verbose_name='parent'),
        ),
    ]
