# Generated by Django 2.1.3 on 2019-09-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0009_auto_20190911_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='layer',
            field=models.IntegerField(default=0, verbose_name='嵌套层数'),
        ),
    ]
