# Generated by Django 2.1.3 on 2019-09-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0011_auto_20190924_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='demo',
            field=models.TextField(default='', verbose_name='api返回格式范例'),
        ),
        migrations.AddField(
            model_name='api',
            name='summary',
            field=models.TextField(default='', verbose_name='api说明'),
        ),
    ]
