# Generated by Django 2.1.3 on 2019-10-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0012_auto_20190930_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='expand_fields',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='展开字段'),
        ),
        migrations.AlterField(
            model_name='api',
            name='ordering',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='排序'),
        ),
    ]
