# Generated by Django 2.1.3 on 2019-10-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0014_auto_20191014_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='is_array',
            field=models.BooleanField(default=False, verbose_name='是否数组'),
        ),
    ]
