# Generated by Django 2.1.3 on 2019-10-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0015_parameter_is_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='layer',
            field=models.IntegerField(default=0, verbose_name='嵌套层数'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api_basebone.Parameter', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.CharField(choices=[('string', '字符串'), ('int', '整数'), ('decimal', '浮点数'), ('boolean', '布尔值'), ('json', 'json格式'), ('object', '复杂类型'), ('PAGE_SIZE', '页长'), ('PAGE_IDX', '页码'), ('pk', '主键')], max_length=20, verbose_name='参数类型'),
        ),
    ]
