# Generated by Django 2.2.9 on 2020-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basebone', '0017_auto_20191101_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='消息'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='object_id',
            field=models.TextField(blank=True, default='', verbose_name='数据ID'),
        ),
    ]
