# Generated by Django 2.1.2 on 2018-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='city',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, '女'), (1, '男')], default=1, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default='无', max_length=20, verbose_name='名称'),
        ),
    ]
