# Generated by Django 2.1.2 on 2018-10-12 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20181011_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('title', models.CharField(blank=True, default='', max_length=20, verbose_name='标题')),
            ],
            options={
                'verbose_name': '船',
                'verbose_name_plural': '船',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='ship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Ship', verbose_name='船'),
        ),
    ]
